### ISSUE TITLE
Undefined reference

### ISSUE THREAD

**Issue by figoxox** [jrmuizel/ssim#1]
I think that you forget add file. When i compile i have the next errors:
/home/figo/Developer/C/ssim/png.c:49: undefined reference to `png_sig_cmp'
/home/figo/Developer/C/ssim/png.c:54: undefined reference to`png_create_read_struct'
/home/figo/Developer/C/ssim/png.c:59: undefined reference to `png_create_info_struct'
/home/figo/Developer/C/ssim/png.c:66: undefined reference to`png_init_io'
/home/figo/Developer/C/ssim/png.c:67: undefined reference to `png_set_sig_bytes'
/home/figo/Developer/C/ssim/png.c:69: undefined reference to`png_read_info'
/home/figo/Developer/C/ssim/png.c:76: undefined reference to `png_set_interlace_handling'
/home/figo/Developer/C/ssim/png.c:77: undefined reference to`png_read_update_info'
/home/figo/Developer/C/ssim/png.c:88: undefined reference to `png_read_image'

I see the file png.c and you make a reference png.h that does not exist.

Greetings

**Comment by jrmuizel** [comment]
png.h is from libpng
